### ISSUE TITLE
サーバーのエラー停止

### ISSUE THREAD

**Issue by taisukef** [jigintern/2020-Cteam#32]
error: Uncaught NotConnected: Transport endpoint is not connected (os error 107)
    at unwrapResponse (rt/10_dispatch_json.js:24:13)
    at sendAsync (rt/10_dispatch_json.js:75:12)
    at async Listener.accept (rt/30_net.js:114:19)
    at async Server.acceptConnAndIterateHttpRequests (server.ts:212:14)
    at async MuxAsyncIterator.callIteratorNext (mux_async_iterator.ts:30:31)

で、終了してしまっていた

**Comment by amami0522** [comment]
SlackにもあがってたURLまわりのやつですかね
if (window.location.host === "localhost:8884") {
    ws = new WebSocket(`ws://localhost:8883/ws`);
  } else if (window.location.host === "t3.intern.jigd.info") {
    ws = new WebSocket(`wss://t3.intern.jigd.info/ws`);
  }
このあたりの
